### PR TITLE
Update to support spark 1.5 and several new features

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
This contains several new feature and improvement including:

* Support spark 1.5 (contains job done by @sparksburnitt @xinyunh and @bomeng);
* Support using astro same as datasource, which will
* Use hive metastore instead a standalone hbase catalog to store meta data(HBaseSQLContext will inherit from HiveContext instead of SQLContext)
* Using stable HBase relase 1.1.2 instead of 0.98 
* Add new operator UPDATE/DELETE

Thanks for your initial work @Zhangshunyu @Sephiroth-Lin

Later I will add more to make it better to use.

### CODE REVIEW

**Comment by WangTaoTheTonic** [comment]
Added https://github.com/WangTaoTheTonic/astro/commit/30ab4518a6813c95a64b21cf03725122db1f23c6 for supporting using astro in datasource way.

**Comment by WangTaoTheTonic** [comment]
Added new commit to support UPDATE and DELETE.

**Comment by chenliang613** [comment]
@WangTaoTheTonic Thanks for you take this PR.

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
add to whitelist

**Comment by WangTaoTheTonic** [comment]
Upgrade HBase version to 1.1.2 which is now a stable release.

**Comment by ravipesala** [comment]
retest this please

**Comment by ravipesala** [comment]
retest this please

**Comment by ravipesala** [comment]
retest this please

**Comment by ravipesala** [comment]
@WangTaoTheTonic  Following testcases are failing. Can you please verify them.
```
org.apache.spark.sql.hbase.api.java.JavaAPISuite.testCreateInsertRetrieveTable
org.apache.spark.sql.hbase.HBaseBulkLoadIntoTableSuite.bulk load for presplit table
org.apache.spark.sql.hbase.HBaseBulkLoadIntoTableSuite.parall bulk load for presplit table
org.apache.spark.sql.hbase.HBaseBulkLoadIntoTableSuite.parall bulk load presplit table with more than 128 regions
org.apache.spark.sql.hbase.HBaseCatalogTestSuite.Create Table
org.apache.spark.sql.hbase.HBaseCatalogTestSuite.Get Table
org.apache.spark.sql.hbase.HBaseCatalogTestSuite.Alter Table
org.apache.spark.sql.hbase.HBaseCatalogTestSuite.Delete Table
org.apache.spark.sql.hbase.HBasePartitionerSuite.test computePredicate in HBasePartition
org.apache.spark.sql.hbase.HBasePartitionerSuite.test k = 8 OR k > 8 (k is int)
org.apache.spark.sql.hbase.HBasePartitionerSuite.test k < 8 AND k > 8 (k is int)
```

**Comment by WangTaoTheTonic** [comment]
When I click the `Details` to get detailed log, it give me a url like "http://localhost:8080/job/AstroPRBuilder/49/". Could you please make it public for convinience?

**Comment by WangTaoTheTonic** [comment]
retest this please

**Comment by WangTaoTheTonic** [comment]
retest this please

**Comment by WangTaoTheTonic** [comment]
I've passed the tests locally with "mvn clean package", but don't know what error do we got here.

**Comment by ravipesala** [comment]
retest this please

**Comment by ravipesala** [comment]
@WangTaoTheTonic Following test case is failing. Please check
```
org.apache.spark.sql.hbase.api.java.JavaAPISuite.testCreateInsertRetrieveTable
```

**Comment by WangTaoTheTonic** [comment]
retest this please

**Comment by WangTaoTheTonic** [comment]
retest this please

**Comment by WangTaoTheTonic** [comment]
retest this please

**Comment by ravipesala** [comment]
LGTM. Thanks for working on this. Merged to master

**Pull request merged**
