### PR TITLE
Update to support spark 1.5 and several new features

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
This contains several new feature and improvement including:

* Support spark 1.5 (contains job done by @sparksburnitt @xinyunh and @bomeng);
* Support using astro same as datasource, which will
* Use hive metastore instead a standalone hbase catalog to store meta data(HBaseSQLContext will inherit from HiveContext instead of SQLContext)
* Using stable HBase relase 1.1.2 instead of 0.98 
* Add new operator UPDATE/DELETE

Thanks for your initial work @Zhangshunyu @Sephiroth-Lin

Later I will add more to make it better to use.

### CODE REVIEW

**Comment by WangTaoTheTonic** [comment]
test this please

**Comment by ravipesala** [comment]
```CREATE TABLE..``` syntax got changed. Is there any reason why you have changed  it?

**Comment by WangTaoTheTonic** [comment]
Yeah...We move those properties like `hbaseTableName`, `tableName`, `keyCols`, `colsMapping` into the Options which is same way with Data Source in SparkSQL.

**Comment by ravipesala** [comment]
Ok.. but the validations are not good in this create ddl parser. Even if simple error in syntax throws always same exception like below.It is very difficult for user to know where he did wrong. And also the current syntax looks little crude way.
```
Exception in thread "main" java.lang.RuntimeException: [1.1] failure: ``load'' expected but identifier CREATE found
```

**Comment by WangTaoTheTonic** [comment]
AFAIK, this could happened same way in same situation in SparkSQL, but I will check if it has a solution to give proper message when the command could not be parsed.

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by ravipesala** [comment]
@WangTaoTheTonic  can you rebase it.

**Comment by ravipesala** [comment]
@WangTaoTheTonic can you rebase it.

**Comment by jackylk** [comment]
@WangTaoTheTonic can you please rebase

**Pull request merged**
