### PR TITLE
Delete the iml file

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
As the iml file is not needed any more and we've already include it in gitignore file, we should delete it.

### CODE REVIEW

**Comment by ravipesala** [comment]
Can one of the admins verify this patch?

**Comment by chenliang613** [comment]
i verified it as per the below steps, it is working.
1.git clone the latest astro project, and delete the file of "spark-hbase_2.10.iml"
2.Use IDEA to import the astro prject, it is working, can load correctly with all dependency.

**Comment by ravipesala** [comment]
ok to test

**Comment by ravipesala** [comment]
LGTM. Thank you @WangTaoTheTonic  and @chenliang613 for working on it. Merged to master.

**Pull request merged**
